CREATE TABLE Enderecos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PessoaId INT FOREIGN KEY REFERENCES Pessoas(Id) NOT NULL,
    Endereco VARCHAR(255) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado VARCHAR(2) NOT NULL
);